#define SERVICE_NAME_MAX_LEN 128
#define DOMAIN_NAME_MAX_LEN 128
enum log_type {
	LOG_TYPE_MEMORY,
	LOG_TYPE_SYSLOG,
	LOG_TYPE_DONTCHANGE,
	LOG_TYPE_NONE
};

enum service_status {
	SERVICE_OFF,
	SERVICE_STOP,
	SERVICE_POST_STOP,
	SERVICE_START,
	SERVICE_POST_START,
	SERVICE_FAILED,
	SERVICE_RESTART,
	SERVICE_POST_RESTART,
	SERVICE_DONTCHANGE,
	SERVICE_ON
};

#define SPAWND_MQ_NAME "/spawnd"

