#!/bin/sh

usage() {
	echo "$0" "<service>"
	exit 1
}

if test $# != 1
then
	usage
fi

echo -n "Stopping $1... "
if spawndctl stop "$1"
then
	while true
	do
		STATUS="`spawndctl status "$1" | cut -d '/' -f 2`"
		test "$STATUS" == OFF && break
	done
	echo Done
else
	echo Failed
fi
