#!/bin/sh

usage() {
	echo "$0" "[domain]"
	exit 0
}

if test $# -gt 1
then
	usage
fi

if test -z "$1"
then
	DOMAIN="default"
else
	DOMAIN="$1"
fi

echo -n > /etc/spawnd/domains/"$DOMAIN"
spawndctl status | while read L
do
	SERVICE="`echo "$L" | cut -f 1 -d '/'`"
	TARGET_STATUS="`echo "$L" | cut -f 3 -d '/'`"
	test "$TARGET_STATUS" != "ON" && continue
	echo "$SERVICE" >> /etc/spawnd/domains/"$DOMAIN"
done
