#!/bin/sh

usage() {
	echo "$0" "<service>"
	exit 1
}

if test $# != 1
then
	usage
fi

RET="`spawndctl status "$1"`"
if test "$RET" = "SRVINC" -o "$RET" = "INVCMD"
then
	echo Unknown service
	exit 1
fi
echo $RET
if test "$RET" = "ON"
then
	exit 0
else
	exit 1
fi
