#!/bin/sh
SERVICE="$1"
DOMAIN="$2"
test -z "$DOMAIN" && DOMAIN=default
if egrep "^$SERVICE$" /etc/spawnd/domains/"$DOMAIN" > /dev/null
then
	echo Already added
else
	echo "$SERVICE" >> /etc/spawnd/domains/"$DOMAIN"
fi
